//! Definition of the `emf-core-base` interface.

use crate::fn_ptr::*;
use crate::version::Version;
use crate::BaseT;

/// Structure describing the `emf-core-base` interface.
#[repr(C)]
#[derive(Copy, Clone)]
pub struct BaseInterface {
    pub interface_version: Version,
    pub cbase_module: *mut BaseT,

    pub sys_lock_fn: SysLockFn,
    pub sys_try_lock_fn: SysTryLockFn,
    pub sys_unlock_fn: SysUnlockFn,
    pub sys_shutdown_fn: SysShutdownFn,
    pub sys_panic_fn: SysPanicFn,
    pub sys_has_function_fn: SysHasFunctionFn,
    pub sys_get_function_fn: SysGetFunctionFn,
    pub sys_get_sync_handler_fn: SysGetSyncHandlerFn,
    pub sys_set_sync_handler_fn: SysSetSyncHandlerFn,

    pub version_construct_short_fn: VersionConstructShortFn,
    pub version_construct_long_fn: VersionConstructLongFn,
    pub version_construct_full_fn: VersionConstructFullFn,
    pub version_construct_from_string_fn: VersionConstructFromStringFn,
    pub version_representation_is_valid_fn: VersionRepresentationIsValidFn,
    pub version_get_short_representation_fn: VersionGetShortRepresentationFn,
    pub version_get_short_representation_length_fn: VersionGetShortRepresentationLengthFn,
    pub version_get_long_representation_fn: VersionGetLongRepresentationFn,
    pub version_get_long_representation_length_fn: VersionGetLongRepresentationLengthFn,
    pub version_get_full_representation_fn: VersionGetFullRepresentationFn,
    pub version_get_full_representation_length_fn: VersionGetFullRepresentationLengthFn,
    pub version_compare_fn: VersionCompareFn,
    pub version_compare_weak_fn: VersionCompareWeakFn,
    pub version_compare_strong_fn: VersionCompareStrongFn,
    pub version_is_compatible_fn: VersionIsCompatibleFn,

    pub library_register_loader_fn: LibraryRegisterLoaderFn,
    pub library_unregister_loader_fn: LibraryUnregisterLoaderFn,
    pub library_get_num_loaders_fn: LibraryGetNumLoadersFn,
    pub library_get_library_types_fn: LibraryGetLibraryTypesFn,
    pub library_get_loader_handle_fn: LibraryGetLoaderHandleFn,
    pub library_type_exists_fn: LibraryTypeExistsFn,
    pub library_library_exists_fn: LibraryLibraryExistsFn,
    pub library_unsafe_create_library_handle_fn: LibraryUnsafeCreateLibraryHandleFn,
    pub library_unsafe_remove_library_handle_fn: LibraryUnsafeRemoveLibraryHandleFn,
    pub library_unsafe_link_library_fn: LibraryUnsafeLinkLibraryFn,
    pub library_unsafe_get_loader_library_handle_fn: LibraryUnsafeGetLoaderLibraryHandleFn,
    pub library_unsafe_get_loader_handle_fn: LibraryUnsafeGetLoaderHandleFn,
    pub library_unsafe_get_loader_interface_fn: LibraryUnsafeGetLoaderInterfaceFn,
    pub library_load_fn: LibraryLoadFn,
    pub library_unload_fn: LibraryUnloadFn,
    pub library_get_data_symbol_fn: LibraryGetDataSymbolFn,
    pub library_get_function_symbol_fn: LibraryGetFunctionSymbolFn,

    pub module_register_loader_fn: ModuleRegisterLoaderFn,
    pub module_unregister_loader_fn: ModuleUnregisterLoaderFn,
    pub module_get_num_loaders_fn: ModuleGetNumLoadersFn,
    pub module_get_module_types_fn: ModuleGetModuleTypesFn,
    pub module_get_num_modules_fn: ModuleGetNumModulesFn,
    pub module_get_modules_fn: ModuleGetModulesFn,
    pub module_get_num_exported_interfaces_fn: ModuleGetNumExportedInterfacesFn,
    pub module_get_exported_interfaces_fn: ModuleGetExportedInterfacesFn,
    pub module_get_loader_handle_fn: ModuleGetLoaderHandleFn,
    pub module_type_exists_fn: ModuleTypeExistsFn,
    pub module_module_exists_fn: ModuleModuleExistsFn,
    pub module_get_exported_interface_handle_fn: ModuleGetExportedInterfaceHandleFn,
    pub module_exported_interface_exists_fn: ModuleExportedInterfaceExistsFn,
    pub module_unsafe_create_module_handle_fn: ModuleUnsafeCreateModuleHandleFn,
    pub module_unsafe_remove_module_handle_fn: ModuleUnsafeRemoveModuleHandleFn,
    pub module_unsafe_link_module_fn: ModuleUnsafeLinkModuleFn,
    pub module_unsafe_get_loader_module_handle_fn: ModuleUnsafeGetLoaderModuleHandleFn,
    pub module_unsafe_get_loader_handle_fn: ModuleUnsafeGetLoaderHandleFn,
    pub module_unsafe_get_loader_fn: ModuleUnsafeGetLoaderFn,
    pub module_add_module_fn: ModuleAddModuleFn,
    pub module_remove_module_fn: ModuleRemoveModuleFn,
    pub module_get_load_dependencies_fn: ModuleGetLoadDependenciesFn,
    pub module_fetch_status_fn: ModuleFetchStatusFn,
    pub module_add_dependency_fn: ModuleAddDependencyFn,
    pub module_remove_dependency_fn: ModuleRemoveDependencyFn,
    pub module_export_interface_fn: ModuleExportInterfaceFn,
    pub module_load_fn: ModuleLoadFn,
    pub module_unload_fn: ModuleUnloadFn,
    pub module_initialize_fn: ModuleInitializeFn,
    pub module_terminate_fn: ModuleTerminateFn,
    pub module_get_module_info_fn: ModuleGetModuleInfoFn,
    pub module_get_exportable_interfaces_fn: ModuleGetExportableInterfacesFn,
    pub module_get_runtime_dependencies_fn: ModuleGetRuntimeDependenciesFn,
    pub module_get_interface_fn: ModuleGetInterfaceFn,
    pub module_get_module_path_fn: ModuleGetModulePathFn,
}
